CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Eventos" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Fecha" date NOT NULL,
    "Lugar" text NOT NULL,
    "Tipo" text NOT NULL,
    CONSTRAINT "PK_Eventos" PRIMARY KEY ("Codigo")
);

CREATE TABLE "Participantes" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Institucion" text NOT NULL,
    "Correo" text NOT NULL,
    CONSTRAINT "PK_Participantes" PRIMARY KEY ("Codigo")
);

CREATE TABLE "Ponentes" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Apellido" text NOT NULL,
    "Institucion" text NOT NULL,
    "Correo" text NOT NULL,
    "CodigoEvento" integer NOT NULL,
    "CodigoSesion" integer NOT NULL,
    CONSTRAINT "PK_Ponentes" PRIMARY KEY ("Codigo")
);

CREATE TABLE "Sesiones" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "HorarioInicio" time without time zone NOT NULL,
    "HorarioFin" time without time zone NOT NULL,
    "Sala" text NOT NULL,
    "CodigoEvento" integer NOT NULL,
    "EventoCodigo" integer,
    CONSTRAINT "PK_Sesiones" PRIMARY KEY ("Codigo"),
    CONSTRAINT "FK_Sesiones_Eventos_EventoCodigo" FOREIGN KEY ("EventoCodigo") REFERENCES "Eventos" ("Codigo")
);

CREATE TABLE "EventoPonente" (
    "EventosCodigo" integer NOT NULL,
    "PonentesCodigo" integer NOT NULL,
    CONSTRAINT "PK_EventoPonente" PRIMARY KEY ("EventosCodigo", "PonentesCodigo"),
    CONSTRAINT "FK_EventoPonente_Eventos_EventosCodigo" FOREIGN KEY ("EventosCodigo") REFERENCES "Eventos" ("Codigo") ON DELETE CASCADE,
    CONSTRAINT "FK_EventoPonente_Ponentes_PonentesCodigo" FOREIGN KEY ("PonentesCodigo") REFERENCES "Ponentes" ("Codigo") ON DELETE CASCADE
);

CREATE TABLE "Inscripciones" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "Estado" boolean NOT NULL,
    "FechaInscripcion" date NOT NULL,
    "CodigoEvento" integer NOT NULL,
    "CodigoParticipante" integer NOT NULL,
    "CodigoSesion" integer NOT NULL,
    "ParticipanteCodigo" integer,
    "EventoCodigo" integer,
    "SesionCodigo" integer,
    CONSTRAINT "PK_Inscripciones" PRIMARY KEY ("Codigo"),
    CONSTRAINT "FK_Inscripciones_Eventos_EventoCodigo" FOREIGN KEY ("EventoCodigo") REFERENCES "Eventos" ("Codigo"),
    CONSTRAINT "FK_Inscripciones_Participantes_ParticipanteCodigo" FOREIGN KEY ("ParticipanteCodigo") REFERENCES "Participantes" ("Codigo"),
    CONSTRAINT "FK_Inscripciones_Sesiones_SesionCodigo" FOREIGN KEY ("SesionCodigo") REFERENCES "Sesiones" ("Codigo")
);

CREATE TABLE "Certificados" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaEmision" timestamp with time zone NOT NULL,
    "Asistencia" boolean NOT NULL,
    "TipoCertificado" text NOT NULL,
    "NombreCertificado" text NOT NULL,
    "Descripcion" text NOT NULL,
    "CodigoInscripcion" integer NOT NULL,
    CONSTRAINT "PK_Certificados" PRIMARY KEY ("Codigo"),
    CONSTRAINT "FK_Certificados_Inscripciones_CodigoInscripcion" FOREIGN KEY ("CodigoInscripcion") REFERENCES "Inscripciones" ("Codigo") ON DELETE CASCADE
);

CREATE TABLE "Pagos" (
    "Codigo" integer GENERATED BY DEFAULT AS IDENTITY,
    "MetodoPago" text NOT NULL,
    "Monto" double precision NOT NULL,
    "Pagado" boolean NOT NULL,
    "CodigoInscripcion" integer NOT NULL,
    CONSTRAINT "PK_Pagos" PRIMARY KEY ("Codigo"),
    CONSTRAINT "FK_Pagos_Inscripciones_CodigoInscripcion" FOREIGN KEY ("CodigoInscripcion") REFERENCES "Inscripciones" ("Codigo") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Certificados_CodigoInscripcion" ON "Certificados" ("CodigoInscripcion");

CREATE INDEX "IX_EventoPonente_PonentesCodigo" ON "EventoPonente" ("PonentesCodigo");

CREATE INDEX "IX_Inscripciones_EventoCodigo" ON "Inscripciones" ("EventoCodigo");

CREATE INDEX "IX_Inscripciones_ParticipanteCodigo" ON "Inscripciones" ("ParticipanteCodigo");

CREATE INDEX "IX_Inscripciones_SesionCodigo" ON "Inscripciones" ("SesionCodigo");

CREATE UNIQUE INDEX "IX_Pagos_CodigoInscripcion" ON "Pagos" ("CodigoInscripcion");

CREATE INDEX "IX_Sesiones_EventoCodigo" ON "Sesiones" ("EventoCodigo");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250509160630_InitialCreate', '8.0.15');

COMMIT;

